version: '2'
services:
  mongo_host:
    image: mongo:latest
    restart: always
    ports: ["27018:27017"]
  postgres_host:
    image: postgres:10-alpine
    restart: always
    ports: ["5433:5432"]
  redis_host:
    image: redis:4.0.11-alpine
    restart: always
    ports: ["6380:6379"]
  data-client:
    build:
      context: ./storage_backend
    depends_on:
      - mongo_host
      - postgres_host
      - redis_host
    tty: true
    environment:
      - APP_MONGO_HOST=mongo_host
      - APP_MONGO_PORT=27017
      - APP_POSTGRES_HOST=postgres_host
      - APP_POSTGRES_PORT=5432
      - APP_REDIS_HOST=redis_host
      - APP_REDIS_PORT=6379
    volumes:
      - /tmp/data:/data
    links: [mongo_host, postgres_host, redis_host]
  flask-app:
    build:
      context: ./flask_app
    depends_on:
      - mongo_host
      - postgres_host
      - redis_host
    tty: true
    environment:
      - APP_MONGO_HOST=mongo_host
      - APP_MONGO_PORT=27017
      - APP_POSTGRES_HOST=postgres_host
      - APP_POSTGRES_PORT=5432
      - APP_REDIS_HOST=redis_host
      - APP_REDIS_PORT=6379
      - BIND_PORT=5001
    volumes:
      - /tmp/data:/data
    links: [mongo_host, postgres_host, redis_host]
    ports:
      - "5001:5001"
    expose:
      - "5001"